import os
import json
import shutil



item_to_label = {
    'armchair': 'Armchairs',
    'rocking chair': 'Armchairs',
    'office chair': 'Armchairs',
    'Lounge Chair / Cafe Chair / Office Chair': 'Armchairs',
    'Dressing Chair': 'Armchairs',
    'Classic Chinese Chair': 'Armchairs',
    'Hanging Chair': 'Armchairs',
    'Lounge Chair / Book-chair / Computer Chair': 'Armchairs',
    'set_of_armchairs': 'Armchairs',
    'computer chair': 'Armchairs',
    'beanbag': 'Armchairs',
    'recliner': 'Armchairs',
    'gaming chair': 'Armchairs',
    'lawn chair': 'Armchairs',
    'deck chair': 'Armchairs',
    'headphones': 'Audio Devices',
    'radio receiver': 'Audio Devices',
    'tape player': 'Audio Devices',
    'phonograph record': 'Audio Devices',
    'radio': 'Audio Devices',
    'record player': 'Audio Devices',
    'record_player': 'Audio Devices',
    'earphone': 'Audio Devices',
    'speaker (stero equipment)': 'Audio Devices',
    'tape recorder': 'Audio Devices',
    'cassette': 'Audio Devices',
    'videotape': 'Audio Devices',
    'subwoofer': 'Audio Devices',
    'boombox': 'Audio Devices',
    'cd player': 'Audio Devices',
    'ipod': 'Audio Devices',
    'headset': 'Audio Devices',
    'record': 'Audio Devices',
    'jukebox': 'Audio Devices',
    'clock radio': 'Audio Devices',
    'stereo': 'Audio Devices',
    'amplifier': 'Audio Devices',
    'turntable': 'Audio Devices',
    'audio equipment': 'Audio Devices',
    'cassette player': 'Audio Devices',
    'stereo (sound system)': 'Audio Devices',
    'shower_tap': 'Bathroom Fixtures',
    'faucet': 'Bathroom Fixtures',
    'tub': 'Bathroom Fixtures',
    'sink': 'Bathroom Fixtures',
    'toilet': 'Bathroom Fixtures',
    'towel rack': 'Bathroom Fixtures',
    'bidet': 'Bathroom Fixtures',
    'bathroom_accessory': 'Bathroom Fixtures',
    'soap_dish': 'Bathroom Fixtures',
    'towel_ring': 'Bathroom Fixtures',
    'toilet_brush': 'Bathroom Fixtures',
    'jacuzzi': 'Bathroom Fixtures',
    'tap': 'Bathroom Fixtures',
    'towel_rack': 'Bathroom Fixtures',
    'bathtub': 'Bathroom Fixtures',
    'shower_door': 'Bathroom Fixtures',
    'shower': 'Bathroom Fixtures',
    'bath_sink': 'Bathroom Fixtures',
    'washbasin': 'Bathroom Fixtures',
    'basin': 'Bathroom Fixtures',
    'urinal': 'Bathroom Fixtures',
    'toilet_stall': 'Bathroom Fixtures',
    'toilet_sink': 'Bathroom Fixtures',
    'showerhead': 'Bathroom Fixtures',
    'shower_hose': 'Bathroom Fixtures',
    'shower_soap_shelf': 'Bathroom Fixtures',
    'bathroom_utensil': 'Bathroom Fixtures',
    'towel_holder': 'Bathroom Fixtures',
    'bathroom_shelf': 'Bathroom Fixtures',
    'toilet_brush_holder': 'Bathroom Fixtures',
    'soap_dispenser': 'Bathroom Fixtures',
    'toilet_bin': 'Bathroom Fixtures',
    'kitchen sink': 'Bathroom Fixtures',
    'shower head': 'Bathroom Fixtures',
    'shower_tap': 'Bathroom Fixtures',
    'headboard': 'Beds',
    'bed': 'Beds',
    'King-size Bed': 'Beds',
    'Bed Frame': 'Beds',
    'Single bed': 'Beds',
    'Kids Bed': 'Beds',
    'Bunk Bed': 'Beds',
    'Double Bed': 'Beds',
    'Couch Bed': 'Beds',
    'bed_small': 'Beds',
    'bedframe': 'Beds',
    'crib': 'Beds',
    'bed frame': 'Beds',
    'bunk bed': 'Beds',
    'ottoman': 'Benches',
    'bench': 'Benches',
    'stool': 'Benches',
    'Footstool / Sofastool / Bed End Stool / Stool': 'Benches',
    'Barstool': 'Benches',
    'bar stool': 'Benches',
    'step stool': 'Benches',
    'pastry': 'Baked Goods',
    'pie': 'Baked Goods',
    'pancake': 'Baked Goods',
    'muffin': 'Baked Goods',
    'cookie': 'Baked Goods',
    'cookies': 'Baked Goods',
    'bread': 'Baked Goods',
    'doughnut': 'Baked Goods',
    'eclair': 'Baked Goods',
    'cracker': 'Baked Goods',
    'cake': 'Baked Goods',
    'donut': 'Baked Goods',
    'birthday cake': 'Baked Goods',
    'bagel': 'Baked Goods',
    'donuts': 'Baked Goods',
    'waffle': 'Baked Goods',
    'bun': 'Baked Goods',
    'fruit juice': 'Beverages',
    'pop (soda)': 'Beverages',
    'drink': 'Beverages',
    'liquor': 'Beverages',
    'alcohol': 'Beverages',
    'orange juice': 'Beverages',
    'beverage': 'Beverages',
    'die': 'Board Games',
    'dice': 'Board Games',
    'chessboard': 'Board Games',
    'chess piece': 'Board Games',
    'game': 'Board Games',
    'token': 'Board Games',
    'dartboard': 'Board Games',
    'video game': 'Board Games',
    'checkerboard': 'Board Games',
    'chess set': 'Board Games',
    'shelf': 'Bookcases',
    'shelves': 'Bookcases',
    'bookcase': 'Bookcases',
    'bookshelf': 'Bookcases',
    'Bookcase / jewelry Armoire': 'Bookcases',
    'Shelf': 'Bookcases',
    'kitchen_shelf': 'Bookcases',
    'book_rack': 'Bookcases',
    'shelving unit': 'Bookcases',
    'hardback book': 'Books & Magazines',
    'book': 'Books & Magazines',
    'magazine': 'Books & Magazines',
    'map': 'Books & Magazines',
    'books': 'Books & Magazines',
    'phonebook': 'Books & Magazines',
    'commode': 'Cabinets (General)',
    'cabinet': 'Cabinets (General)',
    'drawer': 'Cabinets (General)',
    'Drawer Chest / Corner cabinet': 'Cabinets (General)',
    'Wardrobe': 'Cabinets (General)',
    'Children Cabinet': 'Cabinets (General)',
    'Wine Cabinet': 'Cabinets (General)',
    'Shoe Cabinet': 'Cabinets (General)',
    'kitchen_lower_cabinet': 'Cabinets (General)',
    'wine_cabinet': 'Cabinets (General)',
    'sink_cabinet': 'Cabinets (General)',
    'wine_rack': 'Cabinets (General)',
    'jewelry_box': 'Cabinets (General)',
    'wardrobe': 'Cabinets (General)',
    'display_cabinet': 'Cabinets (General)',
    'locker': 'Cabinets (General)',
    'storage_cabinet': 'Cabinets (General)',
    'chest': 'Cabinets (General)',
    'bar_cabinet': 'Cabinets (General)',
    'cupboard': 'Cabinets (General)',
    'armoire': 'Cabinets (General)',
    'cabinets': 'Cabinets (General)',
    'drawers': 'Cabinets (General)',
    'display case': 'Cabinets (General)',
    'closet': 'Cabinets (General)',
    'candle holder': 'Candle Holders',
    'candelabra': 'Candle Holders',
    'candle': 'Candle Holders',
    'shoe': 'Clothing & Accessories',
    'shoes': 'Clothing & Accessories',
    'flip-flop (sandal)': 'Clothing & Accessories',
    'underwear': 'Clothing & Accessories',
    'skirt': 'Clothing & Accessories',
    'hat': 'Clothing & Accessories',
    'baseball cap': 'Clothing & Accessories',
    'sunglasses': 'Clothing & Accessories',
    'glasses': 'Clothing & Accessories',
    'scarf': 'Clothing & Accessories',
    'dress suit': 'Clothing & Accessories',
    'boot': 'Clothing & Accessories',
    'slipper (footwear)': 'Clothing & Accessories',
    'jacket': 'Clothing & Accessories',
    'beanie': 'Clothing & Accessories',
    'belt': 'Clothing & Accessories',
    'shawl': 'Clothing & Accessories',
    'eyeglasses': 'Clothing & Accessories',
    'glove': 'Clothing & Accessories',
    'coat': 'Clothing & Accessories',
    'gloves': 'Clothing & Accessories',
    'jumpsuit': 'Clothing & Accessories',
    'swimsuit': 'Clothing & Accessories',
    'sock': 'Clothing & Accessories',
    'goggles': 'Clothing & Accessories',
    'wet suit': 'Clothing & Accessories',
    'sandal': 'Clothing & Accessories',
    'vest': 'Clothing & Accessories',
    'hairpin': 'Clothing & Accessories',
    'costume': 'Clothing & Accessories',
    'boots': 'Clothing & Accessories',
    'bulletproof vest': 'Clothing & Accessories',
    'spectacles': 'Clothing & Accessories',
    'robe': 'Clothing & Accessories',
    'cap': 'Clothing & Accessories',
    'sandal (type of shoe)': 'Clothing & Accessories',
    'suit (clothing)': 'Clothing & Accessories',
    'brassiere': 'Clothing & Accessories',
    'cape': 'Clothing & Accessories',
    'visor': 'Clothing & Accessories',
    'tennis shoe': 'Clothing & Accessories',
    'cap (headwear)': 'Clothing & Accessories',
    'pajamas': 'Clothing & Accessories',
    'bowler hat': 'Clothing & Accessories',
    'headscarf': 'Clothing & Accessories',
    'eyeglass': 'Clothing & Accessories',
    'broom': 'Cleaning & Maintenance',
    'mop': 'Cleaning & Maintenance',
    'trash can': 'Cleaning & Maintenance',
    'garbage can': 'Cleaning & Maintenance',
    'fire extinguisher': 'Cleaning & Maintenance',
    'scrubbing brush': 'Cleaning & Maintenance',
    'urn': 'Collectible Decor',
    'medal': 'Collectible Decor',
    'badge': 'Collectible Decor',
    'fossil': 'Collectible Decor',
    'gourd': 'Collectible Decor',
    'collectible': 'Collectible Decor',
    'crystal ball': 'Collectible Decor',
    'house model': 'Collectible Decor',
    'pottery': 'Collectible Decor',
    'hourglass': 'Collectible Decor',
    'pinecone': 'Collectible Decor',
    'crown': 'Collectible Decor',
    'gemstone': 'Collectible Decor',
    'artifact': 'Collectible Decor',
    'pocket watch': 'Collectible Decor',
    'trophy cup': 'Collectible Decor',
    'shell': 'Collectible Decor',
    'rocks': 'Collectible Decor',
    'stamp': 'Collectible Decor',
    'cross': 'Collectible Decor',
    'bracelet': 'Collectible Decor',
    'jewelry': 'Collectible Decor',
    'arrowhead': 'Collectible Decor',
    'coral': 'Collectible Decor',
    'coin': 'Collectible Decor',
    'piggy bank': 'Collectible Decor',
    'earring': 'Collectible Decor',
    'ring': 'Collectible Decor',
    'necklace': 'Collectible Decor',
    'pendant': 'Collectible Decor',
    'watch': 'Collectible Decor',
    'seashell': 'Collectible Decor',
    'figurine': 'Collectible Decor',
    'vase': 'Collectible Decor',
    'frame': 'Collectible Decor',
    'globe': 'Collectible Decor',
    'clock': 'Collectible Decor',
    'mask': 'Collectible Decor',
    'keychain': 'Collectible Decor',
    'christmas tree ornament': 'Collectible Decor',
    'painting_frame': 'Collectible Decor',
    'wreath': 'Collectible Decor',
    'photo': 'Collectible Decor',
    'decor': 'Collectible Decor',
    'picture_frame': 'Collectible Decor',
    'photo_mount': 'Collectible Decor',
    'christmas_tree': 'Collectible Decor',
    'bust': 'Collectible Decor',
    'decoration': 'Collectible Decor',
    'decorative_plate': 'Collectible Decor',
    'rock': 'Collectible Decor',
    'art_frame': 'Collectible Decor',
    'ornament': 'Collectible Decor',
    'keyring': 'Collectible Decor',
    'bow': 'Collectible Decor',
    'bead': 'Collectible Decor',
    'trophy': 'Collectible Decor',
    'gingerbread house': 'Collectible Decor',
    'chain': 'Collectible Decor',
    'crystals': 'Collectible Decor',
    'photograph': 'Collectible Decor',
    'fossils': 'Collectible Decor',
    'coaster': 'Collectible Decor',
    'crystal': 'Collectible Decor',
    'place mat': 'Collectible Decor',
    'medallion': 'Collectible Decor',
    'wristband': 'Collectible Decor',
    'charm': 'Collectible Decor',
    'picture frame': 'Collectible Decor',
    'arrow head': 'Collectible Decor',
    'sticker': 'Collectible Decor',
    'belt buckle': 'Collectible Decor',
    'grandfather clock': 'Collectible Decor',
    'snow globe': 'Collectible Decor',
    'acorn': 'Collectible Decor',
    'wristwatch': 'Collectible Decor',
    'award': 'Collectible Decor',
    'coffee table': 'Coffee Tables',
    'Coffee Table': 'Coffee Tables',
    'Corner/Side Table': 'Coffee Tables',
    'Round End Table': 'Coffee Tables',
    'Tea Table': 'Coffee Tables',
    'lamp_table': 'Coffee Tables',
    'end table': 'Coffee Tables',
    'computer': 'Computers (Desktop)',
    'laptop computer': 'Computers (Laptop)',
    'laptop': 'Computers (Laptop)',
    'scissors': 'Cutting Tools',
    'saw': 'Cutting Tools',
    'blade': 'Cutting Tools',
    'handsaw': 'Cutting Tools',
    'knife': 'Cutting Tools',
    'dagger': 'Cutting Tools',
    'ax': 'Cutting Tools',
    'steak knife': 'Cutting Tools',
    'pocketknife': 'Cutting Tools',
    'hand axe': 'Cutting Tools',
    'razorblade': 'Cutting Tools',
    'icecream': 'Dairy Products',
    'milk': 'Dairy Products',
    'yogurt': 'Dairy Products',
    'chocolate milk': 'Dairy Products',
    'milkshake': 'Dairy Products',
    'ice cream': 'Dairy Products',
    'desk': 'Desks',
    'Desk': 'Desks',
    'wall_desk': 'Desks',
    'dj_table': 'Desks',
    'workstation': 'Desks',
    'desk_and_chairs': 'Desks',
    'computer_desk': 'Desks',
    'drawer_desk': 'Desks',
    'highchair': 'Dining Chairs',
    'chair': 'Dining Chairs',
    'Dining Chair': 'Dining Chairs',
    'chairs': 'Dining Chairs',
    'dining table': 'Dining Tables',
    'kitchen table': 'Dining Tables',
    'table': 'Dining Tables',
    'Dining Table': 'Dining Tables',
    'dinner_table': 'Dining Tables',
    'display_table': 'Dining Tables',
    'coffee cup': 'Dishware',
    'teacup': 'Dishware',
    'glass': 'Dishware',
    'wineglass': 'Dishware',
    'chalice': 'Dishware',
    'dish': 'Dishware',
    'gravy boat': 'Dishware',
    'cup': 'Dishware',
    'mug': 'Dishware',
    'bowl': 'Dishware',
    'plate': 'Dishware',
    'teapot': 'Dishware',
    'fruit_bowl': 'Dishware',
    'dinnerware': 'Dishware',
    'cake_stand': 'Dishware',
    'platter': 'Dishware',
    'drinkware': 'Dishware',
    'decorative_bowl': 'Dishware',
    'beer mug': 'Dishware',
    'saucer': 'Dishware',
    'goblet': 'Dishware',
    'glass (drink container)': 'Dishware',
    'dress': 'Dresses',
    'dresser': 'Dressers',
    'bureau': 'Dressers',
    'mousepad': 'Electronic Accessories',
    'outlet': 'Electronic Accessories',
    'plug': 'Electronic Accessories',
    'camera lens': 'Electronic Accessories',
    'flashlight': 'Electronic Accessories',
    'torch': 'Electronic Accessories',
    'lighter': 'Electronic Accessories',
    'socket': 'Electronic Accessories',
    'electric_outlet': 'Electronic Accessories',
    'charger': 'Electronic Accessories',
    'wall socket': 'Electronic Accessories',
    'antenna': 'Electronic Accessories',
    'cable': 'Electronic Accessories',
    'file cabinet': 'File Cabinets',
    'file_cabinet': 'File Cabinets',
    'filing cabinet': 'File Cabinets',
    'folding chair': 'Folding Chairs',
    'Folding chair': 'Folding Chairs',
    'tank (storage vessel)': 'Food Storage Containers',
    'water bottle': 'Food Storage Containers',
    'canteen': 'Food Storage Containers',
    'thermos bottle': 'Food Storage Containers',
    'bottle': 'Food Storage Containers',
    'wine bottle': 'Food Storage Containers',
    'can': 'Food Storage Containers',
    'canister': 'Food Storage Containers',
    'jar': 'Food Storage Containers',
    'bucket': 'Food Storage Containers',
    'barrel': 'Food Storage Containers',
    'jug': 'Food Storage Containers',
    'water jug': 'Food Storage Containers',
    'box': 'Food Storage Containers',
    'crate': 'Food Storage Containers',
    'basket': 'Food Storage Containers',
    'bottles_of_wine': 'Food Storage Containers',
    'soap_bottle': 'Food Storage Containers',
    'container': 'Food Storage Containers',
    'cooler': 'Food Storage Containers',
    'barrels': 'Food Storage Containers',
    'aerosol can': 'Food Storage Containers',
    'beer can': 'Food Storage Containers',
    'spray can': 'Food Storage Containers',
    'tin': 'Food Storage Containers',
    'beer bottle': 'Food Storage Containers',
    'cereal box': 'Food Storage Containers',
    'pill bottle': 'Food Storage Containers',
    'containers': 'Food Storage Containers',
    'cooler (for food)': 'Food Storage Containers',
    'lunchbox': 'Food Storage Containers',
    'milk can': 'Food Storage Containers',
    'pail': 'Food Storage Containers',
    'cannister': 'Food Storage Containers',
    'orange (fruit)': 'Fresh Fruits',
    'pear': 'Fresh Fruits',
    'apple': 'Fresh Fruits',
    'avocado': 'Fresh Fruits',
    'grape': 'Fresh Fruits',
    'banana': 'Fresh Fruits',
    'pineapple': 'Fresh Fruits',
    'lemon': 'Fresh Fruits',
    'watermelon': 'Fresh Fruits',
    'box_of_fruit': 'Fresh Fruits',
    'fruit': 'Fresh Fruits',
    'cantaloup': 'Fresh Fruits',
    'peach': 'Fresh Fruits',
    'coconut': 'Fresh Fruits',
    'mango': 'Fresh Fruits',
    'orange': 'Fresh Fruits',
    'bananas': 'Fresh Fruits',
    'cherry': 'Fresh Fruits',
    'kiwi fruit': 'Fresh Fruits',
    'melon': 'Fresh Fruits',
    'lettuce': 'Fresh Vegetables',
    'bell pepper': 'Fresh Vegetables',
    'pumpkin': 'Fresh Vegetables',
    'broccoli': 'Fresh Vegetables',
    'ginger': 'Fresh Vegetables',
    'tomato': 'Fresh Vegetables',
    'garlic': 'Fresh Vegetables',
    'cucumber': 'Fresh Vegetables',
    'cauliflower': 'Fresh Vegetables',
    'chili (vegetable)': 'Fresh Vegetables',
    'pillow': 'Furniture Accessories',
    'Sideboard / Side Cabinet / Console': 'Furniture Accessories',
    'Bar': 'Furniture Accessories',
    'bar': 'Furniture Accessories',
    'blinds': 'Furniture Accessories',
    'futon': 'Furniture Accessories',
    'footstool': 'Furniture Accessories',
    'mattress': 'Furniture Accessories',
    'coatrack': 'Furniture Accessories',
    'coat hanger': 'Furniture Accessories',
    'cushion': 'Furniture Accessories',
    'pillows': 'Furniture Accessories',
    'door': 'Furniture Accessories',
    'doorway': 'Furniture Accessories',
    'window': 'Furniture Accessories',
    'counter': 'Furniture Accessories',
    'podium': 'Furniture Accessories',
    'stand': 'Furniture Accessories',
    'tray': 'Furniture Accessories',
    'Nightstand': 'Furniture Accessories',
    'TV Stand': 'Furniture Accessories',
    'Sideboard / Side Cabinet / Console Table': 'Furniture Accessories',
    'Dressing Table': 'Furniture Accessories',
    'food_tray': 'Furniture Accessories',
    'art_stand': 'Furniture Accessories',
    'clothes_hanger_rod': 'Furniture Accessories',
    'bed_table': 'Furniture Accessories',
    'window_shutter': 'Furniture Accessories',
    'wall_cubby': 'Furniture Accessories',
    'coat_hanger': 'Furniture Accessories',
    'nightstand': 'Furniture Accessories',
    'tv_stand': 'Furniture Accessories',
    'curtain': 'Furniture Accessories',
    'baby_changing_station': 'Furniture Accessories',
    'window_shade': 'Furniture Accessories',
    'kitchen_counter': 'Furniture Accessories',
    'media_console': 'Furniture Accessories',
    'kitchen_island': 'Furniture Accessories',
    'curtain_rod': 'Furniture Accessories',
    'window_frame': 'Furniture Accessories',
    'chair_stand': 'Furniture Accessories',
    'credenza': 'Furniture Accessories',
    'vanity': 'Furniture Accessories',
    'dressing_table': 'Furniture Accessories',
    'clothes_rack': 'Furniture Accessories',
    'hanger': 'Furniture Accessories',
    'clothes_hanger': 'Furniture Accessories',
    'buffet table': 'Furniture Accessories',
    'bulletin board': 'Furniture Accessories',
    'easel': 'Furniture Accessories',
    'countertop': 'Furniture Accessories',
    'sideboard': 'Furniture Accessories',
    'console table': 'Furniture Accessories',
    'tv stand': 'Furniture Accessories',
    'chalkboard': 'Furniture Accessories',
    'corkboard': 'Furniture Accessories',
    'doors': 'Furniture Accessories',
    'windows': 'Furniture Accessories',
    'doorframe': 'Furniture Accessories',
    'video game console': 'Game Consoles',
    'videogame console': 'Game Consoles',
    'game console': 'Game Consoles',
    'console': 'Game Consoles',
    'game cartridge': 'Game Consoles',
    'handheld game console': 'Handheld Game Consoles',
    'handheld gaming console': 'Handheld Game Consoles',
    'wrench': 'Hand Tools (Wrenches)',
    'hammer': 'Hand Tools (Wrenches)',
    'screwdriver': 'Hand Tools (Wrenches)',
    'pliers': 'Hand Tools (Wrenches)',
    'handbag': 'Handbags',
    'tote bag': 'Handbags',
    'purse': 'Handbags',
    'clutch bag': 'Handbags',
    'briefcase': 'Handbags',
    'bag': 'Handbags',
    'backpack': 'Handbags',
    'wallet': 'Handbags',
    'satchel': 'Handbags',
    'duffel bag': 'Handbags',
    'vacuum_cleaner': 'Home Appliances',
    'automatic washer': 'Home Appliances',
    'fan': 'Home Appliances',
    'air conditioner': 'Home Appliances',
    'ceiling_fan': 'Home Appliances',
    'heater': 'Home Appliances',
    'radiator': 'Home Appliances',
    'washing_machine_and_dryer': 'Home Appliances',
    'air_conditioner': 'Home Appliances',
    'water heater': 'Home Appliances',
    'vacuum cleaner': 'Home Appliances',
    'iron': 'Home Appliances',
    'iron (for clothing)': 'Home Appliances',
    'washing machine': 'Home Appliances',
    'spider': 'Insect',
    'insect': 'Insect',
    'dishwasher': 'Kitchen Appliances',
    'coffee_maker': 'Kitchen Appliances',
    'refrigerator': 'Kitchen Appliances',
    'coffeepot': 'Kitchen Appliances',
    'microwave oven': 'Kitchen Appliances',
    'toaster': 'Kitchen Appliances',
    'toaster oven': 'Kitchen Appliances',
    'microwave': 'Kitchen Appliances',
    'coffee maker': 'Kitchen Appliances',
    'Wine Cooler': 'Kitchen Appliances',
    'cooker': 'Kitchen Appliances',
    'stovetop': 'Kitchen Appliances',
    'grill': 'Kitchen Appliances',
    'cooker_unit': 'Kitchen Appliances',
    'fridge': 'Kitchen Appliances',
    'kitchen_appliance': 'Kitchen Appliances',
    'stove': 'Kitchen Appliances',
    'oven': 'Kitchen Appliances',
    'freezer': 'Kitchen Appliances',
    'coffee_machine': 'Kitchen Appliances',
    'blender': 'Kitchen Appliances',
    'coffee grinder': 'Kitchen Appliances',
    'meat grinder': 'Kitchen Appliances',
    'grinder': 'Kitchen Appliances',
    'teakettle': 'Kitchen Utensils',
    'pitcher (vessel for liquid)': 'Kitchen Utensils',
    'chopstick': 'Kitchen Utensils',
    'spoon': 'Kitchen Utensils',
    'ladle': 'Kitchen Utensils',
    'rolling pin': 'Kitchen Utensils',
    'saltshaker': 'Kitchen Utensils',
    'pan (for cooking)': 'Kitchen Utensils',
    'pan': 'Kitchen Utensils',
    'pot': 'Kitchen Utensils',
    'kettle': 'Kitchen Utensils',
    'pitcher': 'Kitchen Utensils',
    'mixer (kitchen tool)': 'Kitchen Utensils',
    'breadbin': 'Kitchen Utensils',
    'knife_holder': 'Kitchen Utensils',
    'mixer': 'Kitchen Utensils',
    'kitchen_utensil': 'Kitchen Utensils',
    'spice_rack': 'Kitchen Utensils',
    'utensil': 'Kitchen Utensils',
    'fork': 'Kitchen Utensils',
    'cauldron': 'Kitchen Utensils',
    'spatula': 'Kitchen Utensils',
    'cutting board': 'Kitchen Utensils',
    'cooking utensil': 'Kitchen Utensils',
    'saucepan': 'Kitchen Utensils',
    'frying pan': 'Kitchen Utensils',
    'wooden spoon': 'Kitchen Utensils',
    'bottle opener': 'Kitchen Utensils',
    'corkscrew': 'Kitchen Utensils',
    'pepper mill': 'Kitchen Utensils',
    'mortar and pestle': 'Kitchen Utensils',
    'pan (metal container)': 'Kitchen Utensils',
    'eggbeater': 'Kitchen Utensils',
    'floor lamp': 'Lighting',
    'table lamp': 'Lighting',
    'lamp': 'Lighting',
    'oil lamp': 'Lighting',
    'lantern': 'Lighting',
    'light': 'Lighting',
    'Pendant Lamp': 'Lighting',
    'Ceiling Lamp': 'Lighting',
    'Floor Lamp': 'Lighting',
    'Wall Lamp': 'Lighting',
    'lamp_stand': 'Lighting',
    'chandelier': 'Lighting',
    'oil_lamp': 'Lighting',
    'lampshade': 'Lighting',
    'floodlight': 'Lighting',
    'sausage': 'Meats',
    'steak (food)': 'Meats',
    'ham': 'Meats',
    'scale (measuring instrument)': 'Measuring Tools',
    'measuring stick': 'Measuring Tools',
    'ruler': 'Measuring Tools',
    'compass': 'Measuring Tools',
    'scale': 'Measuring Tools',
    'tape measure': 'Measuring Tools',
    'thermometer': 'Measuring Tools',
    'timer': 'Measuring Tools',
    'cellular telephone': 'Mobile Devices',
    'phone': 'Mobile Devices',
    'tablet': 'Mobile Devices',
    'walkie talkie': 'Mobile Devices',
    'cellphone': 'Mobile Devices',
    'musical instrument': 'Musical Instruments',
    'drum (musical instrument)': 'Musical Instruments',
    'cello': 'Musical Instruments',
    'violin': 'Musical Instruments',
    'guitar': 'Musical Instruments',
    'instrument': 'Musical Instruments',
    'piano': 'Musical Instruments',
    'drum': 'Musical Instruments',
    'musical_instrument': 'Musical Instruments',
    'banjo': 'Musical Instruments',
    'saxophone': 'Musical Instruments',
    'trumpet': 'Musical Instruments',
    'router (computer equipment)': 'Network Equipment',
    'modem': 'Network Equipment',
    'router': 'Network Equipment',
    'mouse (computer equipment)': 'Office Electronics',
    'keyboard': 'Office Electronics',
    'remote control': 'Office Electronics',
    'telephone': 'Office Electronics',
    'alarm clock': 'Office Electronics',
    'typewriter': 'Office Electronics',
    'gps': 'Office Electronics',
    'hair dryer': 'Office Electronics',
    'flash drive': 'Office Electronics',
    'disk': 'Office Electronics',
    'disc': 'Office Electronics',
    'monitor (computer equipment) computer monitor': 'Office Electronics',
    'camera': 'Office Electronics',
    'microphone': 'Office Electronics',
    'computer_equipment': 'Office Electronics',
    'printer': 'Office Electronics',
    'speaker': 'Office Electronics',
    'monitor': 'Office Electronics',
    'circuit board': 'Office Electronics',
    'computer keyboard': 'Office Electronics',
    'keypad': 'Office Electronics',
    'webcam': 'Office Electronics',
    'calculator': 'Office Electronics',
    'floppy disk': 'Office Electronics',
    'camcorder': 'Office Electronics',
    'hard drive': 'Office Electronics',
    'computer chip': 'Office Electronics',
    'display': 'Office Electronics',
    'megaphone': 'Office Electronics',
    'joystick': 'Office Electronics',
    'television camera': 'Office Electronics',
    'game controller': 'Office Electronics',
    'controller': 'Office Electronics',
    'usb': 'Office Electronics',
    'pen': 'Office Supplies',
    'marker': 'Office Supplies',
    'pencil': 'Office Supplies',
    'paper': 'Office Supplies',
    'whiteboard': 'Office Supplies',
    'business card': 'Office Supplies',
    'receipt': 'Office Supplies',
    'card': 'Office Supplies',
    'office_utensil': 'Office Supplies',
    'calendar': 'Office Supplies',
    'binder': 'Office Supplies',
    'board': 'Office Supplies',
    'newspaper': 'Office Supplies',
    'stack_of_papers': 'Office Supplies',
    'envelope': 'Office Supplies',
    'notebook': 'Office Supplies',
    'notepad': 'Office Supplies',
    'bookmark': 'Office Supplies',
    'eraser': 'Office Supplies',
    'stapler': 'Office Supplies',
    'pencil sharpener': 'Office Supplies',
    None: 'Others',
    'character': 'Others',
    'cube': 'Others',
    'identity card': 'Others',
    'key': 'Others',
    'helmet': 'Others',
    'butterfly': 'Others',
    'bathrobe': 'Others',
    'horn': 'Others',
    'paintbrush': 'Others',
    'wheel': 'Others',
    'bone': 'Others',
    'cart': 'Others',
    'walking stick': 'Others',
    'paper_towel_dispenser': 'Others',
    'pipe': 'Others',
    'tobacco pipe': 'Others',
    'fish': 'Others',
    'cylinder': 'Others',
    'handcart': 'Others',
    'bicycle': 'Others',
    'money': 'Others',
    'stick': 'Others',
    'case': 'Others',
    'flag': 'Others',
    'cigarettes': 'Others',
    'ashtray': 'Others',
    'cigar box': 'Others',
    'grenade': 'Others',
    'syringe': 'Others',
    'robot': 'Others',
    'duck': 'Others',
    'keg': 'Others',
    'microscope': 'Others',
    'furniture': 'Others',
    'keycard': 'Others',
    'telescope': 'Others',
    'binoculars': 'Others',
    'weapon': 'Others',
    'flask': 'Others',
    'pepper': 'Others',
    'present': 'Others',
    'egg': 'Others',
    'tube': 'Others',
    'mailbox (at home)': 'Others',
    'coloring material': 'Others',
    'control': 'Others',
    'cash register': 'Others',
    'wagon': 'Others',
    'wheelchair': 'Others',
    'object': 'Others',
    'screen': 'Others',
    'garden_bower': 'Others',
    'gym_equipment': 'Others',
    'playground': 'Others',
    'treadmill': 'Others',
    'yard': 'Others',
    'gate': 'Others',
    'umbrella': 'Others',
    'decorative_quilt': 'Others',
    'cover': 'Others',
    'fireplace_utensil': 'Others',
    'cloth': 'Others',
    'gift': 'Others',
    'carpet_roll': 'Others',
    'skateboard': 'Others',
    'shack': 'Others',
    'chimney': 'Others',
    'workout_bike': 'Others',
    'wall': 'Others',
    'soapbox': 'Others',
    'light_switch': 'Others',
    'switch': 'Others',
    'stair_step': 'Others',
    'button': 'Others',
    'tile': 'Others',
    'fire_dish': 'Others',
    'lattice': 'Others',
    'bell': 'Others',
    'sauna_heater': 'Others',
    'beam': 'Others',
    'throw_blanket': 'Others',
    'fountain': 'Others',
    'tripod': 'Others',
    'balcony': 'Others',
    'tissue': 'Others',
    'thermostat': 'Others',
    'fireplace': 'Others',
    'railing': 'Others',
    'ventilation_hood': 'Others',
    'kitchen_wall': 'Others',
    'floor_mat': 'Others',
    'step': 'Others',
    'staircase': 'Others',
    'garage_door': 'Others',
    'dog_bed': 'Others',
    'shower_mat': 'Others',
    'unknown': 'Others',
    'aquarium': 'Others',
    'tablecloth': 'Others',
    'exercise_equipment': 'Others',
    'watering_can': 'Others',
    'mailbox': 'Others',
    'wooden_house': 'Others',
    'bin': 'Others',
    'vent': 'Others',
    'projector_screen': 'Others',
    'furnace': 'Others',
    'wood': 'Others',
    'wheelbarrow': 'Others',
    'panel_screen': 'Others',
    'pillar': 'Others',
    'fireplace_wall': 'Others',
    'weight': 'Others',
    'fencing': 'Others',
    'oven_vent': 'Others',
    'range_hood': 'Others',
    'security_camera': 'Others',
    'slide': 'Others',
    'safe': 'Others',
    'panel': 'Others',
    'hose': 'Others',
    'ping_pong_table': 'Others',
    'motorcycle': 'Others',
    'brush': 'Others',
    'casket': 'Others',
    'rack': 'Others',
    'firewood_holder': 'Others',
    'shower_wall': 'Others',
    'handle': 'Others',
    'knob': 'Others',
    'post': 'Others',
    'car': 'Others',
    'hammock': 'Others',
    'doormat': 'Others',
    'partition': 'Others',
    'tent': 'Others',
    'dumbbell': 'Others',
    'towel': 'Others',
    'roof': 'Others',
    'balcony_railing': 'Others',
    'floor': 'Others',
    'ironing_board': 'Others',
    'carpet': 'Others',
    'stairs': 'Others',
    'rolling_cart': 'Others',
    'blanket': 'Others',
    'appliance': 'Others',
    'wall_panel': 'Others',
    'swing': 'Others',
    'rod': 'Others',
    'machine': 'Others',
    'rocking_horse': 'Others',
    'unknown_wall': 'Others',
    'barbecue': 'Others',
    'desk_clutter': 'Others',
    'sitting_area': 'Others',
    'arcade_game': 'Others',
    'pool': 'Others',
    'mirror': 'Others',
    'boiler': 'Others',
    'sewing_machine': 'Others',
    'person': 'Others',
    'projector': 'Others',
    'water_dispenser': 'Others',
    'mortar': 'Others',
    'seat': 'Others',
    'platform': 'Others',
    'rail': 'Others',
    'bridge': 'Others',
    'sunbed': 'Others',
    'smoke_alarm': 'Others',
    'fence': 'Others',
    'wall_board': 'Others',
    'fire_pit': 'Others',
    'sewing machine': 'Others',
    'cigarette case': 'Others',
    'cork (bottle plug)': 'Others',
    'watering can': 'Others',
    'claw': 'Others',
    'arcade machine': 'Others',
    'football helmet': 'Others',
    'clay': 'Others',
    'walking cane': 'Others',
    'rocking horse': 'Others',
    'dispenser': 'Others',
    'dentures': 'Others',
    'bamboo': 'Others',
    'fishbowl': 'Others',
    'medicine': 'Others',
    'toothpick': 'Others',
    'bow (weapon)': 'Others',
    'cigarette': 'Others',
    'matchbox': 'Others',
    'horseshoe': 'Others',
    'gift wrap': 'Others',
    'baby seat': 'Others',
    'bike': 'Others',
    'cigar': 'Others',
    'stroller': 'Others',
    'unicycle': 'Others',
    'dog collar': 'Others',
    'tag': 'Others',
    'label': 'Others',
    'spyglass': 'Others',
    'barbell': 'Others',
    'tires': 'Others',
    'spool': 'Others',
    'circuit': 'Others',
    'dollar': 'Others',
    'foosball table': 'Others',
    'canvas': 'Others',
    'dough': 'Others',
    'needle': 'Others',
    'cane': 'Others',
    'game table': 'Others',
    'magnet': 'Others',
    'stethoscope': 'Others',
    'lid': 'Others',
    'screw': 'Others',
    'nail': 'Others',
    'bottle cap': 'Others',
    'clam': 'Others',
    'license plate': 'Others',
    'birdhouse': 'Outdoor Decor',
    'ice skate': 'Outdoor Sports Gear',
    'roller skate': 'Outdoor Sports Gear',
    'scooter': 'Outdoor Sports Gear',
    'tricycle': 'Outdoor Sports Gear',
    'surfboard': 'Outdoor Sports Gear',
    'fishing rod': 'Outdoor Sports Gear',
    'bowling pin': 'Outdoor Sports Gear',
    'boomerang': 'Outdoor Sports Gear',
    'bat': 'Outdoor Sports Gear',
    'club': 'Outdoor Sports Gear',
    'golf club': 'Outdoor Sports Gear',
    'paddle': 'Outdoor Sports Gear',
    'arrow': 'Outdoor Sports Gear',
    'basketball backboard': 'Outdoor Sports Gear',
    'frisbee': 'Outdoor Sports Gear',
    'whistle': 'Outdoor Sports Gear',
    'hockey stick': 'Outdoor Sports Gear',
    'snowboard': 'Outdoor Sports Gear',
    'skate': 'Outdoor Sports Gear',
    'sled': 'Outdoor Sports Gear',
    'dart': 'Outdoor Sports Gear',
    'baseball glove': 'Outdoor Sports Gear',
    'pants': 'Pants',
    'sweat pants': 'Pants',
    'tank top (clothing)': 'Pants',
    'short pants': 'Pants',
    'legging (clothing)': 'Pants',
    'shorts': 'Pants',
    'toothbrush': 'Personal Care',
    'hairbrush': 'Personal Care',
    'perfume': 'Personal Care',
    'first-aid kit': 'Personal Care',
    'soap': 'Personal Care',
    'toilet tissue': 'Personal Care',
    'toilet_cleaner': 'Personal Care',
    'toiletry': 'Personal Care',
    'cosmetic': 'Personal Care',
    'hand_wash': 'Personal Care',
    'liquid_soap': 'Personal Care',
    'shampoo': 'Personal Care',
    'toilet_paper': 'Personal Care',
    'paper towel': 'Personal Care',
    'dishtowel': 'Personal Care',
    'diaper': 'Personal Care',
    'beauty products': 'Personal Care',
    'shaver': 'Personal Care',
    'toothpaste': 'Personal Care',
    'first aid kit': 'Personal Care',
    'handkerchief': 'Personal Care',
    'lipstick': 'Personal Care',
    'pacifier': 'Personal Care',
    'lotion': 'Personal Care',
    'razor': 'Personal Care',
    'sponge': 'Personal Care',
    'planter': 'Plant Decor',
    'plant': 'Plant Decor',
    'flower': 'Plant Decor',
    'flower arrangement': 'Plant Decor',
    'flowerpot': 'Plant Decor',
    'flower_stand': 'Plant Decor',
    'rose': 'Plant Decor',
    'sunflower': 'Plant Decor',
    'flowers': 'Plant Decor',
    'potted plant': 'Plant Decor',
    'cactus': 'Plant Decor',
    'bouquet': 'Plant Decor',
    'pizza': 'Prepared Foods',
    'soup': 'Prepared Foods',
    'sandwich': 'Prepared Foods',
    'sushi': 'Prepared Foods',
    'fries': 'Prepared Foods',
    'pasta': 'Prepared Foods',
    'food': 'Prepared Foods',
    'jam': 'Prepared Foods',
    'toast (food)': 'Prepared Foods',
    'hamburger': 'Prepared Foods',
    'hotdog': 'Prepared Foods',
    'taco': 'Prepared Foods',
    'rice': 'Prepared Foods',
    'noodles': 'Prepared Foods',
    'ketchup': 'Prepared Foods',
    'french fries': 'Prepared Foods',
    'rubber duck': 'Puzzle Toys',
    'figure': 'Puzzle Toys',
    'blocks': 'Puzzle Toys',
    'marble': 'Puzzle Toys',
    'wand': 'Puzzle Toys',
    'lightsaber': 'Puzzle Toys',
    'toy': 'Puzzle Toys',
    'teddy bear': 'Puzzle Toys',
    'doll': 'Puzzle Toys',
    'lego': 'Puzzle Toys',
    'block': 'Puzzle Toys',
    'water gun': 'Puzzle Toys',
    'stuffed_animal': 'Puzzle Toys',
    'plush_toy': 'Puzzle Toys',
    'light saber': 'Puzzle Toys',
    'sneakers': 'Sneakers',
    'sneaker': 'Sneakers',
    'sofa': 'Sofas (Multi-Seat)',
    'couch': 'Sofas (Multi-Seat)',
    'Three-Seat / Multi-seat Sofa': 'Sofas (Multi-Seat)',
    'Lazy Sofa': 'Sofas (Multi-Seat)',
    'L-shaped Sofa': 'Sofas (Multi-Seat)',
    'Three-Seat / Multi-person sofa': 'Sofas (Multi-Seat)',
    'Chaise Longue Sofa': 'Sofas (Multi-Seat)',
    'sofa_set': 'Sofas (Multi-Seat)',
    'chaise': 'Sofas (Multi-Seat)',
    'U-shaped Sofa': 'Sofas (Multi-Seat)',
    'chaise longue': 'Sofas (Multi-Seat)',
    'loveseat': 'Sofas (Two-Seat)',
    'Loveseat Sofa': 'Sofas (Two-Seat)',
    'Two-seat Sofa': 'Sofas (Two-Seat)',
    'candy cane': 'Snacks',
    'candy': 'Snacks',
    'popsicle': 'Snacks',
    'chocolate bar': 'Snacks',
    'lollipop': 'Snacks',
    'crisp (potato chip)': 'Snacks',
    'popcorn': 'Snacks',
    'peanut': 'Snacks',
    'candy bar': 'Snacks',
    'nut': 'Snacks',
    'balls': 'Sports Balls',
    'soccer ball': 'Sports Balls',
    'ball': 'Sports Balls',
    'basketball': 'Sports Balls',
    'football': 'Sports Balls',
    'football (american)': 'Sports Balls',
    'volleyball': 'Sports Balls',
    'baseball': 'Sports Balls',
    'golf ball': 'Sports Balls',
    'football card': 'Sports Collectibles',
    'baseball card': 'Sports Collectibles',
    'trading card': 'Sports Collectibles',
    'basketball card': 'Sports Collectibles',
    'pool table': 'Sports Collectibles',
    'pool_table': 'Sports Collectibles',
    'trading cards': 'Sports Collectibles',
    'pokemon card': 'Sports Collectibles',
    'game card': 'Sports Collectibles',
    'sports card': 'Sports Collectibles',
    'carton': 'Storage Boxes',
    'pouch': 'Storage Boxes',
    'packet': 'Storage Boxes',
    'newspaper_basket': 'Storage Boxes',
    'tissue_box': 'Storage Boxes',
    'towel_basket': 'Storage Boxes',
    'laundry_basket': 'Storage Boxes',
    'storage': 'Storage Boxes',
    'box_of_tissue': 'Storage Boxes',
    'storage_box': 'Storage Boxes',
    'hamper': 'Storage Boxes',
    'clothes hamper': 'Storage Boxes',
    'hatbox': 'Storage Boxes',
    'package': 'Storage Boxes',
    'cardboard box': 'Storage Boxes',
    'trunk': 'Suitcases',
    'suitcase': 'Suitcases',
    'sweater': 'Sweaters',
    'stepladder': 'Tools',
    'mallet': 'Tools',
    'crowbar': 'Tools',
    'chisel': 'Tools',
    'nailfile': 'Tools',
    'tool': 'Tools',
    'drill': 'Tools',
    'toolbox': 'Tools',
    'shovel': 'Tools',
    'ladder': 'Tools',
    'pick axe': 'Tools',
    'clamp': 'Tools',
    'pitchfork': 'Tools',
    'pickaxe': 'Tools',
    'spade': 'Tools',
    'power tool': 'Tools',
    'top': 'Tops (Shirts)',
    'jersey': 'Tops (Shirts)',
    'sweatshirt': 'Tops (Shirts)',
    'blouse': 'Tops (Shirts)',
    'clothing': 'Tops (Shirts)',
    'shirt': 'Tops (Shirts)',
    'clothes': 'Tops (Shirts)',
    'hanging_clothes': 'Tops (Shirts)',
    't-shirt': 'Tops (Shirts)',
    'polo shirt': 'Tops (Shirts)',
    'television': 'TVs',
    'television set': 'TVs',
    'tv': 'TVs',
    'led_tv': 'TVs',
    'artwork': 'Wall Decor',
    'plaque': 'Wall Decor',
    'sculpture': 'Wall Decor',
    'statue (sculpture)': 'Wall Decor',
    'statue': 'Wall Decor',
    'painting': 'Wall Decor',
    'picture': 'Wall Decor',
    'poster': 'Wall Decor',
    'sign': 'Wall Decor',
    'street sign': 'Wall Decor',
    'brass plaque': 'Wall Decor',
    'wall clock': 'Wall Decor'
}



def read_json_file(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
        return data

def save_json_file(data, file_path):
    with open(file_path, 'w') as file:
        file.write(json.dumps(data, indent=4))


if __name__ == "__main__":
    mate_data = read_json_file("data/assets.json")
    labels = []
    for data in mate_data:
        path = os.path.join("data", data["path"])
        if not os.path.isfile(path):
            print(path)

        label = data["label"]
        if not label in labels:
            labels.append(label)

    save_json_file(labels, "data/labels.json")

